id: arduino:dbstorage_tsstore
name: Database - Time Series
description: "Simplified time series database storage layer for Arduino sensor samples built on top of InfluxDB."
requires_container: true
category: storage
variables:
- name: DB_USERNAME
  description: Database username
  default_value: admin
- name: DB_PASSWORD
  description: Database password
  default_value: Arduino15
- name: INFLUXDB_ADMIN_TOKEN
  description: InfluxDB admin token
  default_value: 392edbf2-b8a2-481f-979d-3f188b2c05f0  
- name: BIND_ADDRESS
  description: External container address
  hidden: true
  default_value: 127.0.0.1