id: arduino:video_object_detection
name: Video Object Detection
description: |
  This object detection brick utilizes a pre-trained model to analyze video streams from a camera.
  It identifies objects, returning their predicted class labels, bounding boxes, and confidence scores.
  The output is a video stream featuring bounding boxes around detected objects, with the added capability to trigger actions based on these detections.
  It supports pre-trained models provided by the framework and custom object detection models trained on the Edge Impulse platform.
requires_model: true
requires_container: true
mount_devices_into_container: true
required_devices:
  - camera
model: yolox-object-detection
model_configuration_variables:
  - EI_V_OBJ_DETECTION_MODEL
variables:
- name: EI_V_OBJ_DETECTION_MODEL
  description: Path to the model file
  hidden: true
  default_value: /models/ootb/ei/yolox-object-detection.eim
- name: CUSTOM_MODEL_PATH
  description: Path to the custom model directory
  hidden: true
  default_value: /home/arduino/.arduino-bricks/ei-models
- name: BIND_ADDRESS
  description: Bind address
  hidden: true
  default_value: 127.0.0.1
- name: VIDEO_DEVICE
  description: Video device path
  hidden: true
  default_value: /dev/video1