id: arduino:video_object_tracking
name: Video Object Tracking
description: |
  This object detection brick utilizes a pre-trained model to track objects on a video stream.
  It identifies and tracks objects, returning their predicted class labels and item counts.
  The output is a video stream featuring bounding boxes around tracked objects, enabling object count.
  It supports pre-trained models provided by the framework and custom object detection models trained on the Edge Impulse platform.
requires_model: true
requires_container: true
mount_devices_into_container: true
required_devices:
  - camera
model: yolox-object-detection
model_configuration_variables:
  - EI_OBJ_DETECTION_MODEL