id: arduino:visual_anomaly_detection
name: Visual Anomaly Detection
description: |
  Brick for visual anomaly detection using a pre-trained model. It processes images to identify unusual patterns and returns detected anomalies with bounding boxes. 
  Supports pre-trained models provided by the framework or custom anomaly detection models trained on the Edge Impulse platform. 
category: image
requires_container: true
requires_model: true
model: concrete-crack-anomaly-detection
model_configuration_variables:
  - EI_V_ANOMALY_DETECTION_MODEL
variables:
- name: EI_V_ANOMALY_DETECTION_MODEL
  description: Path to the model file
  private: true
- name: CUSTOM_MODEL_PATH
  description: Path to the custom model directory
  private: true
- name: BIND_ADDRESS
  description: Bind address
  private: true
