id: arduino:object_detection
name: Object Detection
description: |
  Brick for object detection using a pre-trained model. It processes images and returns the predicted class label, bounding-boxes and confidence score.
  Brick is designed to work with pre-trained models provided by framework or with custom object detection models trained on Edge Impulse platform. 
category: video
requires_container: true
requires_model: true
model: yolox-object-detection
model_configuration_variables:
  - EI_OBJ_DETECTION_MODEL
variables:
- name: EI_OBJ_DETECTION_MODEL
  description: Path to the model file
  private: true
- name: CUSTOM_MODEL_PATH
  description: Path to the custom model directory
  private: true
- name: BIND_ADDRESS
  description: Bind address
  private: true  