id: arduino:vibration_anomaly_detection
name: Vibration Anomaly detection
description: |
  This Brick is designed for vibration anomaly detection and recognition, leveraging pre-trained models.
  It takes input from sensors (accelerometer) to identify possible anomalies based on vibration patterns.
  You can use it with pre-trained models provided by the framework or with your own custom anomaly detections models trained on the Edge Impulse platform.
requires_container: true
requires_model: true
model: fan-anomaly-detection
model_configuration_variables:
  - EI_VIBRATION_ANOMALY_DETECTION_MODEL
variables:
- name: EI_VIBRATION_ANOMALY_DETECTION_MODEL
  description: Path to the model file
  hidden: true
  default_value: /models/ootb/ei/fan-anomaly-detection.eim
- name: CUSTOM_MODEL_PATH
  description: Path to the custom model directory
  hidden: true
  default_value: /home/arduino/.arduino-bricks/ei-models
- name: BIND_ADDRESS
  description: Bind address
  hidden: true
  default_value: 127.0.0.1
